name: fix_my_city
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0 
  flutter_map: ^8.2.1 
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  path_provider: ^2.1.2
  image_picker: ^1.0.5
  flutter_svg: ^2.0.10
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/avatar.png
    - assets/pothole1.png
    - assets/sewer_leakage.png
    - assets/streetlight.png
    - assets/pothole_detail.png
    - assets/avni_gupta.png
    - assets/trash_bins.png
    - assets/water_pipe.png
    - assets/arjun_sharma.png
    - assets/priya_singh.png
    - assets/rajesh_kumar.png
    - assets/meera_patel.png
    - assets/icons/home.svg
    - assets/icons/map.svg
    - assets/icons/reports.svg
    - assets/icons/community.svg
    - assets/icons/profile.svg
    - assets/icons/language-translate.svg


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21